name: quote_page
timestamp: 1596130500
version: 7
preset:
  image: 'gantry-admin://images/layouts/2-col-left.png'
  name: form_sidebar
  timestamp: 1591397015
positions:
  widget-quote-page: 'Quote Page'
  breadcrumbs: Breadcrumbs
  header: 'Widget Position'
  footer: Footer
sections:
  header: Header
  Heading: Heading
  mainbottom: Mainbottom
  sidebar: Sidebar
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  title:
    title-6742: Title
  position:
    position-sidebar: 'Quote Page'
    position-breadcrumbs: Breadcrumbs
    position-position-2354: 'Widget Position'
    position-position-2004: Footer
  social:
    social-8763: Social
    social-6894: Social
  messages:
    system-messages-4752: 'System Messages'
  content:
    system-content-3154: 'Page Content'
  logo:
    logo-9339: Logo
    logo-9373: 'Logo / Image'
  menu:
    menu-7803: Menu
  copyright:
    copyright-8461: Copyright
  totop:
    totop-9167: 'To Top'
  mobile-menu:
    mobile-menu-3412: 'Mobile Menu'
inherit:
  default:
    header: header
    footer: footer
    offcanvas: offcanvas
    logo-9339: logo-2741
    menu-7803: menu-2967
    position-position-2354: position-position-7248
    position-position-2004: position-footer
    logo-9373: logo-4026
    copyright-8461: copyright-4409
    social-6894: social-7254
    totop-9167: totop-8211
    mobile-menu-3412: mobile-menu-1009
