name: home-2
timestamp: 1593452226
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home2
  timestamp: 1593451023
positions:
  partners: partners
  widget-quote: 'Home Quote'
  header: Header
  footer: Footer
sections:
  header: Header
  mainsection: Mainsection
  mainsection-1: Mainsection-1
  mainsection-2: Mainsection-2
  mainsection-3: Mainsection-3
  footer: Footer
  offcanvas: Offcanvas
particles:
  sample:
    sample-3705: 'Sample Content'
    sample-9218: 'Sample Content'
    sample-5591: Why
  custom:
    custom-4341: 'Custom HTML'
    custom-7270: 'Custom HTML'
    custom-5781: 'Custom HTML'
  position:
    position-position-6000: partners
    position-position-9059: 'Home Quote'
    position-position-8061: Header
    position-position-5856: Footer
  logo:
    logo-8089: Logo
    logo-2059: 'Logo / Image'
  menu:
    menu-6591: Menu
  copyright:
    copyright-1541: Copyright
  social:
    social-2690: Social
  totop:
    totop-6678: 'To Top'
  mobile-menu:
    mobile-menu-6335: Mobile-menu
  messages:
    system-messages-6357: 'System Messages'
  order_steps_particle:
    order_steps_particle-5863: 'Order Steps'
inherit:
  default:
    header: header
    footer: footer
    offcanvas: offcanvas
    logo-8089: logo-2741
    menu-6591: menu-4332
    position-position-8061: position-header
    position-position-5856: position-footer
    logo-2059: logo-4026
    copyright-1541: copyright-4409
    social-2690: social-7254
    totop-6678: totop-8211
    mobile-menu-6335: mobile-menu-9981
  home:
    mainsection: mainsection
    mainsection-1: mainsection-1
    system-messages-6357: system-messages-1543
    custom-5781: custom-7960
    sample-5591: sample-7236
    order_steps_particle-5863: order_steps_particle-3390
