name: leisure_pools
timestamp: 1596130499
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1587844427
positions:
  breadcrumbs: Breadcrumbs
  header: 'Widget Position'
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-breadcrumbs: Breadcrumbs
    position-position-2009: 'Widget Position'
    position-position-8963: Footer
  messages:
    system-messages-5215: 'System Messages'
  title:
    title-5129: Title
  content:
    system-content-7581: 'Page Content'
  logo:
    logo-7308: Logo
    logo-8656: 'Logo / Image'
  menu:
    menu-9799: Menu
  copyright:
    copyright-1620: Copyright
  social:
    social-7582: Social
  totop:
    totop-3265: 'To Top'
  mobile-menu:
    mobile-menu-6412: 'Mobile Menu'
inherit:
  default:
    header: header
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-7308: logo-2741
    menu-9799: menu-2967
    position-position-2009: position-position-7248
    position-position-8963: position-footer
    logo-8656: logo-4026
    copyright-1620: copyright-4409
    social-7582: social-7254
    totop-3265: totop-8211
    mobile-menu-6412: mobile-menu-1009
