version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1587844427
layout:
  header: {  }
  navigation: {  }
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-5215
    -
      - title-5129
    -
      - system-content-7581
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - children
        - attributes
content:
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  title-5129:
    attributes:
      headline: 'Leisure Pools'
      description: 'Aqua Med Pools exclusively offer Leisure Fiberglass Pools. Simply put, Leisure Pools manufactures the strongest, more durable fiberglass pool on the market today with a warranty no other manufacturer comes close to. Whether youâ€™re in Dighton, Dartmourth or Provincetown or anywhere in between, call us today and ask us how we can help you live the Life of Leisure.  '
    block:
      variations: center
