version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1587844427
layout:
  header: {  }
  navigation: {  }
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-5215
    -
      - title-5129
    -
      - system-content-7581
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - children
        - attributes
content:
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  title-5129:
    attributes:
      headline: 'Leisure Pools'
      header: ''
      description: 'Aqua Med Pools exclusively offer Leisure Fiberglass Pools. Simply put, Leisure Pools manufactures the strongest, more durable fiberglass pool on the market today with a warranty no other manufacturer comes close to. To our Cape Customers in Bourne, Sandwich, Falmouth, Mashpee, Barnstable, Yarmouth, Dennis, Harwich, Brewster, Chatham, Orleans, Eastham, Wellfleet, Truro, Provincetown, or anywhere in between please look over the fiberglass pool models we offer and reach out to us, ask us how we can help you live the Life of Leisure. YOU could be swimming in just ONE WEEK!'
    block:
      variations: center
