name: pools_page
timestamp: 1591895392
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1587844427
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5018: Logo
    logo-3154: 'Logo / Image'
  menu:
    menu-7603: Menu
  position:
    position-position-4607: Header
    position-breadcrumbs: Breadcrumbs
    position-position-8610: Footer
  title:
    title-4207: Title
    title-4784: why
  page_links:
    page_links-4295: 'Page links'
  custom:
    custom-8237: 'Custom HTML'
    custom-4639: 'Custom HTML'
  messages:
    system-messages-6637: 'System Messages'
  content:
    system-content-8969: 'Page Content'
  copyright:
    copyright-1574: Copyright
  social:
    social-8871: Social
  totop:
    totop-3944: 'To Top'
  mobile-menu:
    mobile-menu-2293: Mobile-menu
inherit:
  default:
    header: header
    logo-5018: logo-2741
    menu-7603: menu-4332
    position-position-4607: position-header
    navigation: navigation
    footer: footer
    position-position-8610: position-footer
    logo-3154: logo-4026
    copyright-1574: copyright-4409
    social-8871: social-7254
    totop-3944: totop-8211
    offcanvas: offcanvas
    mobile-menu-2293: mobile-menu-9981
