version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: 4-rows
  timestamp: 1593705436
layout:
  header: {  }
  mainsection: {  }
  /mainsection-1/:
    -
      - system-content-5575
    -
      - html_link-6144
  mainsection-2: {  }
  mainsection-3: {  }
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  mainsection:
    type: section
    inherit:
      outline: gallery
      include:
        - attributes
        - block
        - children
  mainsection-1:
    type: section
    attributes:
      boxed: '2'
      class: ''
      variations: ''
  mainsection-2:
    type: section
    inherit:
      outline: gallery
      include:
        - attributes
        - block
        - children
  mainsection-3:
    type: section
    inherit:
      outline: gallery
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-content-5575:
    inherit:
      outline: gallery-4
      include:
        - attributes
        - block
      particle: system-content-8679
  html_link-6144:
    title: 'HTML Link'
    attributes:
      linkbefore: 'http://localhost/aquamed/gallery/page-4/'
      linktextbefore: PREVIOUS
