name: gallery
timestamp: 1596130499
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: 4-rows
  timestamp: 1593705436
positions:
  header: 'Widget Position'
  footer: Footer
sections:
  header: Header
  mainsection: Mainsection
  mainsection-1: Mainsection-1
  mainsection-2: Mainsection-2
  mainsection-3: Mainsection-3
  footer: Footer
  offcanvas: Offcanvas
particles:
  title:
    title-2592: Title
  content:
    system-content-7678: 'Page Content'
  html_link:
    html_link-6191: 'HTML Link'
  logo:
    logo-5909: Logo
    logo-5957: 'Logo / Image'
  menu:
    menu-2087: Menu
  position:
    position-position-7143: 'Widget Position'
    position-position-8121: Footer
  copyright:
    copyright-5855: Copyright
  social:
    social-6047: Social
  totop:
    totop-1010: 'To Top'
  mobile-menu:
    mobile-menu-2595: 'Mobile Menu'
inherit:
  default:
    header: header
    footer: footer
    offcanvas: offcanvas
    logo-5909: logo-2741
    menu-2087: menu-2967
    position-position-7143: position-position-7248
    position-position-8121: position-footer
    logo-5957: logo-4026
    copyright-5855: copyright-4409
    social-6047: social-7254
    totop-1010: totop-8211
    mobile-menu-2595: mobile-menu-1009
