name: home
timestamp: 1590870030
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1589570910
positions:
  header: Header
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  mainbottom: Mainbottom
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-7960: 'Custom HTML'
  messages:
    system-messages-1543: 'System Messages'
  sample:
    sample-7236: Why
  order_steps_particle:
    order_steps_particle-3390: 'Order Steps'
  logo:
    logo-5127: Logo
    logo-9210: 'Logo / Image'
  menu:
    menu-9606: Menu
  position:
    position-position-5859: Header
    position-position-2513: Footer
  copyright:
    copyright-3536: Copyright
  social:
    social-6816: Social
  totop:
    totop-2266: 'To Top'
  mobile-menu:
    mobile-menu-2417: Mobile-menu
inherit:
  default:
    header: header
    navigation: navigation
    system-messages-1543: system-messages-7126
    footer: footer
    offcanvas: offcanvas
    logo-5127: logo-2741
    menu-9606: menu-4332
    position-position-5859: position-header
    position-position-2513: position-footer
    logo-9210: logo-4026
    copyright-3536: copyright-4409
    social-6816: social-7254
    totop-2266: totop-8211
    mobile-menu-2417: mobile-menu-9981
