name: home
timestamp: 1593452226
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1593450754
positions:
  header: Header
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  mainsection: Mainsection
  mainsection-1: Mainsection-1
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3055: Logo
    logo-5917: 'Logo / Image'
  menu:
    menu-2140: Menu
  position:
    position-position-9312: Header
    position-position-1706: Footer
  messages:
    system-messages-1543: 'System Messages'
  custom:
    custom-7960: 'Custom HTML'
  sample:
    sample-7236: Why
  order_steps_particle:
    order_steps_particle-3390: 'Order Steps'
  copyright:
    copyright-8847: Copyright
  social:
    social-2772: Social
  totop:
    totop-1512: 'To Top'
  mobile-menu:
    mobile-menu-2442: Mobile-menu
inherit:
  default:
    header: header
    logo-3055: logo-2741
    menu-2140: menu-4332
    position-position-9312: position-header
    navigation: navigation
    system-messages-1543: system-messages-7126
    footer: footer
    position-position-1706: position-footer
    logo-5917: logo-4026
    copyright-8847: copyright-4409
    social-2772: social-7254
    totop-1512: totop-8211
    offcanvas: offcanvas
    mobile-menu-2442: mobile-menu-9981
