name: home
timestamp: 1596130499
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1593450754
positions:
  header: 'Widget Position'
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  mainsection: Mainsection
  mainsection-1: Mainsection-1
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-1543: 'System Messages'
  custom:
    custom-7960: 'Custom HTML'
  sample:
    sample-7236: Why
  order_steps_particle:
    order_steps_particle-3390: 'Order Steps'
  logo:
    logo-3055: Logo
    logo-5917: 'Logo / Image'
  menu:
    menu-8998: Menu
  position:
    position-position-7859: 'Widget Position'
    position-position-1706: Footer
  copyright:
    copyright-8847: Copyright
  social:
    social-2772: Social
  totop:
    totop-1512: 'To Top'
  mobile-menu:
    mobile-menu-6682: 'Mobile Menu'
inherit:
  default:
    header: header
    navigation: navigation
    system-messages-1543: system-messages-7126
    footer: footer
    offcanvas: offcanvas
    logo-3055: logo-2741
    menu-8998: menu-2967
    position-position-7859: position-position-7248
    position-position-1706: position-footer
    logo-5917: logo-4026
    copyright-8847: copyright-4409
    social-2772: social-7254
    totop-1512: totop-8211
    mobile-menu-6682: mobile-menu-1009
