name: gallery-3
timestamp: 1595012724
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: 4-rows
  timestamp: 1593705436
positions:
  header: 'Widget Position'
  footer: Footer
sections:
  header: Header
  mainsection: Mainsection
  mainsection-1: Mainsection-1
  mainsection-2: Mainsection-2
  mainsection-3: Mainsection-3
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-6946: 'Page Content'
  html_link:
    html_link-1884: 'HTML Link'
  logo:
    logo-4476: Logo
    logo-3794: 'Logo / Image'
  menu:
    menu-4148: Menu
  position:
    position-position-1324: 'Widget Position'
    position-position-6771: Footer
  copyright:
    copyright-2327: Copyright
  social:
    social-2948: Social
  totop:
    totop-6403: 'To Top'
  mobile-menu:
    mobile-menu-4150: 'Mobile Menu'
  title:
    title-1806: Title
inherit:
  default:
    header: header
    footer: footer
    offcanvas: offcanvas
    logo-4476: logo-2741
    menu-4148: menu-4332
    position-position-1324: position-position-7248
    position-position-6771: position-footer
    logo-3794: logo-4026
    copyright-2327: copyright-4409
    social-2948: social-7254
    totop-6403: totop-8211
    mobile-menu-4150: mobile-menu-1009
  gallery:
    mainsection: mainsection
    mainsection-2: mainsection-2
    mainsection-3: mainsection-3
    title-1806: title-2592
  gallery-2:
    system-content-6946: system-content-9479
