name: _offline
timestamp: 1596133270
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1587844427
positions:
  header: 'Widget Position'
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Untitled
particles:
  logo:
    logo-4895: Logo
    logo-3495: 'Logo / Image'
  menu:
    menu-4492: Menu
  position:
    position-position-9742: 'Widget Position'
    position-breadcrumbs: Breadcrumbs
    position-position-7485: Footer
  messages:
    system-messages-6142: 'System Messages'
  content:
    system-content-5929: 'Page Content'
  copyright:
    copyright-6146: Copyright
  social:
    social-7140: Social
  totop:
    totop-4673: 'To Top'
  mobile-menu:
    mobile-menu-9416: 'Mobile Menu'
inherit:
  default:
    header: header
    logo-4895: logo-2741
    menu-4492: menu-2967
    position-position-9742: position-position-7248
    navigation: navigation
    footer: footer
    position-position-7485: position-footer
    logo-3495: logo-4026
    copyright-6146: copyright-4409
    social-7140: social-7254
    totop-4673: totop-8211
    offcanvas: offcanvas
    mobile-menu-9416: mobile-menu-1009
