version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1587844427
layout:
  /header/:
    -
      - 'logo-3511 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-5424
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-6142
    -
      - system-content-5929
  /footer/:
    -
      - position-footer
    -
      - 'copyright-2296 40'
      - 'spacer-3570 30'
      - 'branding-8760 30'
  offcanvas:
    -
      - mobile-menu-3589
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
