ordering:
  about: ''
  pools:
    leisure-pools: ''
    thursday-pools: ''
    other-services: ''
  gallery: ''
  our-prices: ''
  partners:
    leisure-pools: ''
    thursday-pools: ''
  contact-us: ''
  __widget-4lrhM: ''
items:
  about:
    object_id: 8
  pools:
    object_id: 18
  pools/leisure-pools:
    object_id: 246
  pools/thursday-pools:
    object_id: 244
  pools/other-services:
    object_id: 44
  gallery:
    object_id: 12
  our-prices:
    object_id: 14
  partners:
    object_id: 10
  partners/leisure-pools:
    object_id: 458
  partners/thursday-pools:
    object_id: 460
  contact-us:
    object_id: 16
  __widget-4lrhM:
    type: particle
    particle: widget
    title: Search
    options:
      particle:
        enabled: 1
        widget:
          type: widget
          widget: search
          title: Search
          options:
            widget:
              title: ''
      block:
        extra: {  }
