name: gallery-4
timestamp: 1593799852
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: 4-rows
  timestamp: 1593705436
positions:
  header: Header
  footer: Footer
sections:
  header: Header
  mainsection: Mainsection
  mainsection-1: Mainsection-1
  mainsection-2: Mainsection-2
  mainsection-3: Mainsection-3
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9310: Logo
    logo-5679: 'Logo / Image'
  menu:
    menu-6438: Menu
  position:
    position-position-2806: Header
    position-position-5004: Footer
  title:
    title-2108: Title
  content:
    system-content-8679: 'Page Content'
  html_link:
    html_link-2778: 'HTML Link'
  copyright:
    copyright-5229: Copyright
  social:
    social-4549: Social
  totop:
    totop-8702: 'To Top'
  mobile-menu:
    mobile-menu-9603: Mobile-menu
inherit:
  default:
    header: header
    logo-9310: logo-2741
    menu-6438: menu-4332
    position-position-2806: position-header
    footer: footer
    position-position-5004: position-footer
    logo-5679: logo-4026
    copyright-5229: copyright-4409
    social-4549: social-7254
    totop-8702: totop-8211
    offcanvas: offcanvas
    mobile-menu-9603: mobile-menu-9981
  gallery:
    mainsection: mainsection
    title-2108: title-2592
    mainsection-2: mainsection-2
    mainsection-3: mainsection-3
  gallery-3:
    system-content-8679: system-content-6946
