name: thursday_pools
timestamp: 1596130500
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1587844427
positions:
  breadcrumbs: Breadcrumbs
  header: 'Widget Position'
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-breadcrumbs: Breadcrumbs
    position-position-2195: 'Widget Position'
    position-position-4623: Footer
  messages:
    system-messages-6504: 'System Messages'
  title:
    title-2900: Title
  content:
    system-content-2067: 'Page Content'
  logo:
    logo-4368: Logo
    logo-2764: 'Logo / Image'
  menu:
    menu-8105: Menu
  copyright:
    copyright-9603: Copyright
  social:
    social-4972: Social
  totop:
    totop-3714: 'To Top'
  mobile-menu:
    mobile-menu-8193: 'Mobile Menu'
inherit:
  default:
    header: header
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-4368: logo-2741
    menu-8105: menu-2967
    position-position-2195: position-position-7248
    position-position-4623: position-footer
    logo-2764: logo-4026
    copyright-9603: copyright-4409
    social-4972: social-7254
    totop-3714: totop-8211
    mobile-menu-8193: mobile-menu-1009
