name: about
timestamp: 1596130499
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: 4-rows
  timestamp: 1593452544
positions:
  breadcrumbs: Breadcrumbs
  header: 'Widget Position'
  footer: Footer
sections:
  header: Header
  mainsection: Mainsection
  mainsection-1: Mainsection-1
  mainsection-2: Mainsection-2
  mainsection-3: Mainsection-3
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-breadcrumbs: Breadcrumbs
    position-position-2908: 'Widget Position'
    position-position-9580: Footer
  messages:
    system-messages-2630: 'System Messages'
  title:
    title-9051: Title
  experience:
    experience-6836: Experience
  mission:
    mission-8453: Mission
  logo:
    logo-3341: Logo
    logo-9228: 'Logo / Image'
  menu:
    menu-6917: Menu
  copyright:
    copyright-4880: Copyright
  social:
    social-9898: Social
  totop:
    totop-4585: 'To Top'
  mobile-menu:
    mobile-menu-1924: 'Mobile Menu'
inherit:
  default:
    header: header
    footer: footer
    offcanvas: offcanvas
    logo-3341: logo-2741
    menu-6917: menu-2967
    position-position-2908: position-position-7248
    position-position-9580: position-footer
    logo-9228: logo-4026
    copyright-4880: copyright-4409
    social-9898: social-7254
    totop-4585: totop-8211
    mobile-menu-1924: mobile-menu-1009
